name: helper_package
description: A new Flutter package project.
version: 0.0.2
homepage: https://icodeforyou.com

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=3.10.5"

dependencies:
  flutter:
    sdk: flutter
  flutter_image_compress: ^2.0.3  # Flutter plugin for cropping and getting the file path of the cropped image
  flutter_modular: ^5.0.3         # Smart project structure with dependency injection and route management
  hive_flutter: ^1.1.0            # Lightweight and blazing fast key-value database written 
  hooks_riverpod: ^2.3.6          # A state-management library
  image_picker: ^1.0.0            # Flutter plugin for selecting images from the Android and iOS image library
  intl: ^0.18.1                   # For DateTime extensions
  path_provider: ^2.0.15          # Flutter plugin for getting commonly used locations on the Android & iOS file systems
  riverpod_annotation: ^2.1.1     # This is a side package for riverpod_generator, exposing annotations
  uuid: ^3.0.7                    # RFC4122 (v1, v4, v5) UUID Generator and Parser for Web, VM, Flutter

# dart run build_runner build -d
dev_dependencies:
  build_runner: ^2.4.5
  flutter_gen_runner: ^5.3.1
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.2.3        # Different syntax for defining "providers" by relying on code generation.
  riverpod_lint: ^1.3.2             # help stop common issues and simplify repetitive tasks.

flutter:
